// ============================================
// LIB - API functions and storage helpers
// ============================================

// This file handles all data fetching and storage for the app.
// We use free public APIs to get country data, travel guides, and photos.
//
// Data sources:
//  - REST Countries API: https://restcountries.com (country information)
//  - Wikipedia API: https://en.wikipedia.org (travel guides and nearby attractions)
//  - Unsplash API: https://unsplash.com (destination photos, optional)

// API base URLs
const COUNTRIES_API_URL = "https://restcountries.com/v3.1";
const WIKIPEDIA_API_URL = "https://en.wikipedia.org/w/api.php";
const WIKIPEDIA_SUMMARY_URL =
  "https://en.wikipedia.org/api/rest_v1/page/summary";
const UNSPLASH_API_KEY = import.meta.env.VITE_UNSPLASH_ACCESS_KEY;

// Simple cache to avoid fetching the same data twice
const dataCache = new Map();

// This function fetches data and caches it so we don't make duplicate requests
async function fetchWithCache(cacheKey, fetchFunction) {
  // If we already have this data cached, return it
  if (dataCache.has(cacheKey)) {
    return dataCache.get(cacheKey);
  }

  // Otherwise, fetch the data
  const fetchPromise = fetchFunction();
  dataCache.set(cacheKey, fetchPromise);

  try {
    const result = await fetchPromise;
    return result;
  } catch (error) {
    // If the fetch fails, remove it from cache so we can try again
    dataCache.delete(cacheKey);
    throw error;
  }
}

// ============================================
// STORAGE HELPERS - LocalStorage functions
// ============================================

// We use 'atlasora' as a prefix for all our localStorage keys
const STORAGE_PREFIX = "atlasora";

// Read data from localStorage
// If the key doesn't exist or parsing fails, return the fallback value
export function readFromStorage(key, fallbackValue) {
  try {
    const fullKey = `${STORAGE_PREFIX}:${key}`;
    const rawData = localStorage.getItem(fullKey);

    if (rawData === null) {
      return fallbackValue;
    }

    return JSON.parse(rawData);
  } catch (error) {
    // If something goes wrong, just return the fallback
    return fallbackValue;
  }
}

// Write data to localStorage
// If storage is full or unavailable, we fail silently
export function writeToStorage(key, value) {
  try {
    const fullKey = `${STORAGE_PREFIX}:${key}`;
    const jsonString = JSON.stringify(value);
    localStorage.setItem(fullKey, jsonString);
  } catch (error) {
    // Storage might be full or in private mode - just ignore
    console.warn("Could not save to storage:", error);
  }
}

// Remove a specific key from localStorage
export function removeFromStorage(key) {
  const fullKey = `${STORAGE_PREFIX}:${key}`;
  localStorage.removeItem(fullKey);
}

// ============================================
// COUNTRY DATA API FUNCTIONS
// ============================================

// These are the specific fields we want from the countries API
const COUNTRY_FIELDS_TO_FETCH =
  "name,cca2,cca3,capital,region,subregion,population,area,flags,latlng,languages,currencies,timezones,borders,maps,independent";

// This is our backup data in case the API is down
// It contains major countries from all regions so the app still works offline
const FALLBACK_COUNTRIES = [
  // Asia
  {
    name: { common: "Japan" },
    cca2: "JP",
    cca3: "JPN",
    capital: ["Tokyo"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 125800000,
    area: 377975,
    flags: { svg: "https://flagcdn.com/jp.svg" },
    latlng: [36, 138],
    currencies: { JPY: { name: "Japanese yen" } },
    languages: { jpn: "Japanese" },
    timezones: ["UTC+09:00"],
    independent: true,
  },
  {
    name: { common: "India" },
    cca2: "IN",
    cca3: "IND",
    capital: ["New Delhi"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 1380000000,
    area: 3287263,
    flags: { svg: "https://flagcdn.com/in.svg" },
    latlng: [20, 77],
    currencies: { INR: { name: "Indian rupee" } },
    languages: { hin: "Hindi", eng: "English" },
    timezones: ["UTC+05:30"],
    independent: true,
  },
  {
    name: { common: "China" },
    cca2: "CN",
    cca3: "CHN",
    capital: ["Beijing"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 1400000000,
    area: 9596960,
    flags: { svg: "https://flagcdn.com/cn.svg" },
    latlng: [35, 105],
    currencies: { CNY: { name: "Chinese yuan" } },
    languages: { zho: "Chinese" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "South Korea" },
    cca2: "KR",
    cca3: "KOR",
    capital: ["Seoul"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 51780000,
    area: 100210,
    flags: { svg: "https://flagcdn.com/kr.svg" },
    latlng: [37, 127],
    currencies: { KRW: { name: "South Korean won" } },
    languages: { kor: "Korean" },
    timezones: ["UTC+09:00"],
    independent: true,
  },
  {
    name: { common: "Indonesia" },
    cca2: "ID",
    cca3: "IDN",
    capital: ["Jakarta"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 273500000,
    area: 1904569,
    flags: { svg: "https://flagcdn.com/id.svg" },
    latlng: [-5, 120],
    currencies: { IDR: { name: "Indonesian rupiah" } },
    languages: { ind: "Indonesian" },
    timezones: ["UTC+07:00"],
    independent: true,
  },
  {
    name: { common: "Pakistan" },
    cca2: "PK",
    cca3: "PAK",
    capital: ["Islamabad"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 220900000,
    area: 881913,
    flags: { svg: "https://flagcdn.com/pk.svg" },
    latlng: [30, 69],
    currencies: { PKR: { name: "Pakistani rupee" } },
    languages: { eng: "English", urd: "Urdu" },
    timezones: ["UTC+05:00"],
    independent: true,
  },
  {
    name: { common: "Bangladesh" },
    cca2: "BD",
    cca3: "BGD",
    capital: ["Dhaka"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 164700000,
    area: 147570,
    flags: { svg: "https://flagcdn.com/bd.svg" },
    latlng: [24, 90],
    currencies: { BDT: { name: "Bangladeshi taka" } },
    languages: { ben: "Bengali" },
    timezones: ["UTC+06:00"],
    independent: true,
  },
  {
    name: { common: "Philippines" },
    cca2: "PH",
    cca3: "PHL",
    capital: ["Manila"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 109600000,
    area: 300000,
    flags: { svg: "https://flagcdn.com/ph.svg" },
    latlng: [13, 122],
    currencies: { PHP: { name: "Philippine peso" } },
    languages: { eng: "English", fil: "Filipino" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "Vietnam" },
    cca2: "VN",
    cca3: "VNM",
    capital: ["Hanoi"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 97340000,
    area: 331212,
    flags: { svg: "https://flagcdn.com/vn.svg" },
    latlng: [14, 108],
    currencies: { VND: { name: "Vietnamese đồng" } },
    languages: { vie: "Vietnamese" },
    timezones: ["UTC+07:00"],
    independent: true,
  },
  {
    name: { common: "Thailand" },
    cca2: "TH",
    cca3: "THA",
    capital: ["Bangkok"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 69790000,
    area: 513120,
    flags: { svg: "https://flagcdn.com/th.svg" },
    latlng: [15, 101],
    currencies: { THB: { name: "Thai baht" } },
    languages: { tha: "Thai" },
    timezones: ["UTC+07:00"],
    independent: true,
  },
  {
    name: { common: "Turkey" },
    cca2: "TR",
    cca3: "TUR",
    capital: ["Ankara"],
    region: "Asia",
    subregion: "Western Asia",
    population: 84330000,
    area: 783562,
    flags: { svg: "https://flagcdn.com/tr.svg" },
    latlng: [39, 35],
    currencies: { TRY: { name: "Turkish lira" } },
    languages: { tur: "Turkish" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Iran" },
    cca2: "IR",
    cca3: "IRN",
    capital: ["Tehran"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 83990000,
    area: 1648195,
    flags: { svg: "https://flagcdn.com/ir.svg" },
    latlng: [32, 53],
    currencies: { IRR: { name: "Iranian rial" } },
    languages: { fas: "Persian" },
    timezones: ["UTC+03:30"],
    independent: true,
  },
  {
    name: { common: "Saudi Arabia" },
    cca2: "SA",
    cca3: "SAU",
    capital: ["Riyadh"],
    region: "Asia",
    subregion: "Western Asia",
    population: 34810000,
    area: 2149690,
    flags: { svg: "https://flagcdn.com/sa.svg" },
    latlng: [24, 45],
    currencies: { SAR: { name: "Saudi riyal" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Malaysia" },
    cca2: "MY",
    cca3: "MYS",
    capital: ["Kuala Lumpur"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 32370000,
    area: 330803,
    flags: { svg: "https://flagcdn.com/my.svg" },
    latlng: [2, 112],
    currencies: { MYR: { name: "Malaysian ringgit" } },
    languages: { eng: "English", msa: "Malay" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "Myanmar" },
    cca2: "MM",
    cca3: "MMR",
    capital: ["Naypyidaw"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 54410000,
    area: 676578,
    flags: { svg: "https://flagcdn.com/mm.svg" },
    latlng: [22, 98],
    currencies: { MMK: { name: "Myanmar kyat" } },
    languages: { mya: "Burmese" },
    timezones: ["UTC+06:30"],
    independent: true,
  },
  {
    name: { common: "Afghanistan" },
    cca2: "AF",
    cca3: "AFG",
    capital: ["Kabul"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 38930000,
    area: 652230,
    flags: { svg: "https://flagcdn.com/af.svg" },
    latlng: [33, 65],
    currencies: { AFN: { name: "Afghan afghani" } },
    languages: { pus: "Pashto", dar: "Dari" },
    timezones: ["UTC+04:30"],
    independent: true,
  },
  {
    name: { common: "Nepal" },
    cca2: "NP",
    cca3: "NPL",
    capital: ["Kathmandu"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 29140000,
    area: 147181,
    flags: { svg: "https://flagcdn.com/np.svg" },
    latlng: [28, 84],
    currencies: { NPR: { name: "Nepalese rupee" } },
    languages: { nep: "Nepali" },
    timezones: ["UTC+05:45"],
    independent: true,
  },
  {
    name: { common: "Sri Lanka" },
    cca2: "LK",
    cca3: "LKA",
    capital: ["Colombo"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 21920000,
    area: 65610,
    flags: { svg: "https://flagcdn.com/lk.svg" },
    latlng: [7, 81],
    currencies: { LKR: { name: "Sri Lankan rupee" } },
    languages: { sin: "Sinhala", tam: "Tamil" },
    timezones: ["UTC+05:30"],
    independent: true,
  },
  {
    name: { common: "Singapore" },
    cca2: "SG",
    cca3: "SGP",
    capital: ["Singapore"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 5850000,
    area: 697,
    flags: { svg: "https://flagcdn.com/sg.svg" },
    latlng: [1, 103],
    currencies: { SGD: { name: "Singapore dollar" } },
    languages: { eng: "English", msa: "Malay", zho: "Chinese", tam: "Tamil" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "Israel" },
    cca2: "IL",
    cca3: "ISR",
    capital: ["Jerusalem"],
    region: "Asia",
    subregion: "Western Asia",
    population: 8655000,
    area: 20772,
    flags: { svg: "https://flagcdn.com/il.svg" },
    latlng: [31, 35],
    currencies: { ILS: { name: "Israeli new shekel" } },
    languages: { heb: "Hebrew", ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "United Arab Emirates" },
    cca2: "AE",
    cca3: "ARE",
    capital: ["Abu Dhabi"],
    region: "Asia",
    subregion: "Western Asia",
    population: 9890000,
    area: 83600,
    flags: { svg: "https://flagcdn.com/ae.svg" },
    latlng: [24, 54],
    currencies: { AED: { name: "UAE dirham" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+04:00"],
    independent: true,
  },
  {
    name: { common: "Iraq" },
    cca2: "IQ",
    cca3: "IRQ",
    capital: ["Baghdad"],
    region: "Asia",
    subregion: "Western Asia",
    population: 40220000,
    area: 438317,
    flags: { svg: "https://flagcdn.com/iq.svg" },
    latlng: [33, 44],
    currencies: { IQD: { name: "Iraqi dinar" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Syria" },
    cca2: "SY",
    cca3: "SYR",
    capital: ["Damascus"],
    region: "Asia",
    subregion: "Western Asia",
    population: 17500000,
    area: 185180,
    flags: { svg: "https://flagcdn.com/sy.svg" },
    latlng: [35, 38],
    currencies: { SYP: { name: "Syrian pound" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Jordan" },
    cca2: "JO",
    cca3: "JOR",
    capital: ["Amman"],
    region: "Asia",
    subregion: "Western Asia",
    population: 10200000,
    area: 89342,
    flags: { svg: "https://flagcdn.com/jo.svg" },
    latlng: [31, 36],
    currencies: { JOD: { name: "Jordanian dinar" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Lebanon" },
    cca2: "LB",
    cca3: "LBN",
    capital: ["Beirut"],
    region: "Asia",
    subregion: "Western Asia",
    population: 6825000,
    area: 10452,
    flags: { svg: "https://flagcdn.com/lb.svg" },
    latlng: [34, 36],
    currencies: { LBP: { name: "Lebanese pound" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Kuwait" },
    cca2: "KW",
    cca3: "KWT",
    capital: ["Kuwait City"],
    region: "Asia",
    subregion: "Western Asia",
    population: 4271000,
    area: 17818,
    flags: { svg: "https://flagcdn.com/kw.svg" },
    latlng: [29, 46],
    currencies: { KWD: { name: "Kuwaiti dinar" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Qatar" },
    cca2: "QA",
    cca3: "QAT",
    capital: ["Doha"],
    region: "Asia",
    subregion: "Western Asia",
    population: 2881000,
    area: 11586,
    flags: { svg: "https://flagcdn.com/qa.svg" },
    latlng: [25, 51],
    currencies: { QAR: { name: "Qatari riyal" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Oman" },
    cca2: "OM",
    cca3: "OMN",
    capital: ["Muscat"],
    region: "Asia",
    subregion: "Western Asia",
    population: 5107000,
    area: 309500,
    flags: { svg: "https://flagcdn.com/om.svg" },
    latlng: [21, 57],
    currencies: { OMR: { name: "Omani rial" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+04:00"],
    independent: true,
  },
  {
    name: { common: "Yemen" },
    cca2: "YE",
    cca3: "YEM",
    capital: ["Sana'a"],
    region: "Asia",
    subregion: "Western Asia",
    population: 29830000,
    area: 527968,
    flags: { svg: "https://flagcdn.com/ye.svg" },
    latlng: [15, 48],
    currencies: { YER: { name: "Yemeni rial" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Kazakhstan" },
    cca2: "KZ",
    cca3: "KAZ",
    capital: ["Astana"],
    region: "Asia",
    subregion: "Central Asia",
    population: 18770000,
    area: 2724900,
    flags: { svg: "https://flagcdn.com/kz.svg" },
    latlng: [48, 68],
    currencies: { KZT: { name: "Kazakhstani tenge" } },
    languages: { kaz: "Kazakh", rus: "Russian" },
    timezones: ["UTC+06:00"],
    independent: true,
  },
  {
    name: { common: "Uzbekistan" },
    cca2: "UZ",
    cca3: "UZB",
    capital: ["Tashkent"],
    region: "Asia",
    subregion: "Central Asia",
    population: 33470000,
    area: 447400,
    flags: { svg: "https://flagcdn.com/uz.svg" },
    latlng: [41, 64],
    currencies: { UZS: { name: "Uzbekistani so'm" } },
    languages: { uzb: "Uzbek" },
    timezones: ["UTC+05:00"],
    independent: true,
  },
  {
    name: { common: "Turkmenistan" },
    cca2: "TM",
    cca3: "TKM",
    capital: ["Ashgabat"],
    region: "Asia",
    subregion: "Central Asia",
    population: 5942000,
    area: 488100,
    flags: { svg: "https://flagcdn.com/tm.svg" },
    latlng: [39, 59],
    currencies: { TMT: { name: "Turkmenistan manat" } },
    languages: { tuk: "Turkmen" },
    timezones: ["UTC+05:00"],
    independent: true,
  },
  {
    name: { common: "Kyrgyzstan" },
    cca2: "KG",
    cca3: "KGZ",
    capital: ["Bishkek"],
    region: "Asia",
    subregion: "Central Asia",
    population: 6524000,
    area: 199951,
    flags: { svg: "https://flagcdn.com/kg.svg" },
    latlng: [41, 75],
    currencies: { KGS: { name: "Kyrgyzstani som" } },
    languages: { kir: "Kyrgyz", rus: "Russian" },
    timezones: ["UTC+06:00"],
    independent: true,
  },
  {
    name: { common: "Tajikistan" },
    cca2: "TJ",
    cca3: "TJK",
    capital: ["Dushanbe"],
    region: "Asia",
    subregion: "Central Asia",
    population: 9537000,
    area: 143100,
    flags: { svg: "https://flagcdn.com/tj.svg" },
    latlng: [39, 71],
    currencies: { TJS: { name: "Tajikistani somoni" } },
    languages: { tgk: "Tajik" },
    timezones: ["UTC+05:00"],
    independent: true,
  },
  {
    name: { common: "Mongolia" },
    cca2: "MN",
    cca3: "MNG",
    capital: ["Ulaanbaatar"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 3278000,
    area: 1564116,
    flags: { svg: "https://flagcdn.com/mn.svg" },
    latlng: [46, 105],
    currencies: { MNT: { name: "Mongolian tögrög" } },
    languages: { mon: "Mongolian" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "North Korea" },
    cca2: "KP",
    cca3: "PRK",
    capital: ["Pyongyang"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 25780000,
    area: 120538,
    flags: { svg: "https://flagcdn.com/kp.svg" },
    latlng: [40, 127],
    currencies: { KPW: { name: "North Korean won" } },
    languages: { kor: "Korean" },
    timezones: ["UTC+09:00"],
    independent: true,
  },
  {
    name: { common: "Taiwan" },
    cca2: "TW",
    cca3: "TWN",
    capital: ["Taipei"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 23570000,
    area: 36197,
    flags: { svg: "https://flagcdn.com/tw.svg" },
    latlng: [24, 121],
    currencies: { TWD: { name: "New Taiwan dollar" } },
    languages: { zho: "Chinese" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "Hong Kong" },
    cca2: "HK",
    cca3: "HKG",
    capital: ["City of Victoria"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 7497000,
    area: 1104,
    flags: { svg: "https://flagcdn.com/hk.svg" },
    latlng: [22, 114],
    currencies: { HKD: { name: "Hong Kong dollar" } },
    languages: { eng: "English", zho: "Chinese" },
    timezones: ["UTC+08:00"],
    independent: false,
  },
  {
    name: { common: "Macau" },
    cca2: "MO",
    cca3: "MAC",
    capital: ["Macau"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 6493000,
    area: 30,
    flags: { svg: "https://flagcdn.com/mo.svg" },
    latlng: [22, 113],
    currencies: { MOP: { name: "Macanese pataca" } },
    languages: { por: "Portuguese", zho: "Chinese" },
    timezones: ["UTC+08:00"],
    independent: false,
  },
  {
    name: { common: "Cambodia" },
    cca2: "KH",
    cca3: "KHM",
    capital: ["Phnom Penh"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 16720000,
    area: 181035,
    flags: { svg: "https://flagcdn.com/kh.svg" },
    latlng: [13, 105],
    currencies: { KHR: { name: "Cambodian riel" } },
    languages: { khm: "Khmer" },
    timezones: ["UTC+07:00"],
    independent: true,
  },
  {
    name: { common: "Laos" },
    cca2: "LA",
    cca3: "LAO",
    capital: ["Vientiane"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 7276000,
    area: 236800,
    flags: { svg: "https://flagcdn.com/la.svg" },
    latlng: [18, 105],
    currencies: { LAK: { name: "Lao kip" } },
    languages: { lao: "Lao" },
    timezones: ["UTC+07:00"],
    independent: true,
  },
  {
    name: { common: "Brunei" },
    cca2: "BN",
    cca3: "BRN",
    capital: ["Bandar Seri Begawan"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 437500,
    area: 5765,
    flags: { svg: "https://flagcdn.com/bn.svg" },
    latlng: [4, 114],
    currencies: { BND: { name: "Brunei dollar" } },
    languages: { msa: "Malay" },
    timezones: ["UTC+08:00"],
    independent: true,
  },
  {
    name: { common: "Bhutan" },
    cca2: "BT",
    cca3: "BTN",
    capital: ["Thimphu"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 771000,
    area: 38394,
    flags: { svg: "https://flagcdn.com/bt.svg" },
    latlng: [27, 90],
    currencies: { BTN: { name: "Bhutanese ngultrum" } },
    languages: { dzg: "Dzongkha" },
    timezones: ["UTC+06:00"],
    independent: true,
  },
  {
    name: { common: "Maldives" },
    cca2: "MV",
    cca3: "MDV",
    capital: ["Malé"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 540500,
    area: 298,
    flags: { svg: "https://flagcdn.com/mv.svg" },
    latlng: [3, 73],
    currencies: { MVR: { name: "Maldivian rufiyaa" } },
    languages: { div: "Dhivehi" },
    timezones: ["UTC+05:00"],
    independent: true,
  },

  // Europe
  {
    name: { common: "Germany" },
    cca2: "DE",
    cca3: "DEU",
    capital: ["Berlin"],
    region: "Europe",
    subregion: "Western Europe",
    population: 83240000,
    area: 357022,
    flags: { svg: "https://flagcdn.com/de.svg" },
    latlng: [51, 9],
    currencies: { EUR: { name: "Euro" } },
    languages: { deu: "German" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "France" },
    cca2: "FR",
    cca3: "FRA",
    capital: ["Paris"],
    region: "Europe",
    subregion: "Western Europe",
    population: 67390000,
    area: 551695,
    flags: { svg: "https://flagcdn.com/fr.svg" },
    latlng: [46, 2],
    currencies: { EUR: { name: "Euro" } },
    languages: { fra: "French" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "United Kingdom" },
    cca2: "GB",
    cca3: "GBR",
    capital: ["London"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 67330000,
    area: 242495,
    flags: { svg: "https://flagcdn.com/gb.svg" },
    latlng: [55, -3],
    currencies: { GBP: { name: "British pound" } },
    languages: { eng: "English" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Italy" },
    cca2: "IT",
    cca3: "ITA",
    capital: ["Rome"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 59550000,
    area: 301340,
    flags: { svg: "https://flagcdn.com/it.svg" },
    latlng: [42, 12],
    currencies: { EUR: { name: "Euro" } },
    languages: { ita: "Italian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Spain" },
    cca2: "ES",
    cca3: "ESP",
    capital: ["Madrid"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 47350000,
    area: 505992,
    flags: { svg: "https://flagcdn.com/es.svg" },
    latlng: [40, -4],
    currencies: { EUR: { name: "Euro" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Poland" },
    cca2: "PL",
    cca3: "POL",
    capital: ["Warsaw"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 37840000,
    area: 312696,
    flags: { svg: "https://flagcdn.com/pl.svg" },
    latlng: [52, 20],
    currencies: { PLN: { name: "Polish złoty" } },
    languages: { pol: "Polish" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Ukraine" },
    cca2: "UA",
    cca3: "UKR",
    capital: ["Kyiv"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 44130000,
    area: 603550,
    flags: { svg: "https://flagcdn.com/ua.svg" },
    latlng: [49, 32],
    currencies: { UAH: { name: "Ukrainian hryvnia" } },
    languages: { ukr: "Ukrainian" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Romania" },
    cca2: "RO",
    cca3: "ROU",
    capital: ["Bucharest"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 19230000,
    area: 238397,
    flags: { svg: "https://flagcdn.com/ro.svg" },
    latlng: [46, 25],
    currencies: { RON: { name: "Romanian leu" } },
    languages: { ron: "Romanian" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Netherlands" },
    cca2: "NL",
    cca3: "NLD",
    capital: ["Amsterdam"],
    region: "Europe",
    subregion: "Western Europe",
    population: 17130000,
    area: 41543,
    flags: { svg: "https://flagcdn.com/nl.svg" },
    latlng: [52, 5],
    currencies: { EUR: { name: "Euro" } },
    languages: { nld: "Dutch" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Belgium" },
    cca2: "BE",
    cca3: "BEL",
    capital: ["Brussels"],
    region: "Europe",
    subregion: "Western Europe",
    population: 11550000,
    area: 30528,
    flags: { svg: "https://flagcdn.com/be.svg" },
    latlng: [50, 4],
    currencies: { EUR: { name: "Euro" } },
    languages: { nld: "Dutch", fra: "French", deu: "German" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Czech Republic" },
    cca2: "CZ",
    cca3: "CZE",
    capital: ["Prague"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 10710000,
    area: 78867,
    flags: { svg: "https://flagcdn.com/cz.svg" },
    latlng: [49, 15],
    currencies: { CZK: { name: "Czech koruna" } },
    languages: { ces: "Czech" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Greece" },
    cca2: "GR",
    cca3: "GRC",
    capital: ["Athens"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 10420000,
    area: 131957,
    flags: { svg: "https://flagcdn.com/gr.svg" },
    latlng: [39, 22],
    currencies: { EUR: { name: "Euro" } },
    languages: { ell: "Greek" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Portugal" },
    cca2: "PT",
    cca3: "PRT",
    capital: ["Lisbon"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 10170000,
    area: 92212,
    flags: { svg: "https://flagcdn.com/pt.svg" },
    latlng: [39, -8],
    currencies: { EUR: { name: "Euro" } },
    languages: { por: "Portuguese" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Sweden" },
    cca2: "SE",
    cca3: "SWE",
    capital: ["Stockholm"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 10380000,
    area: 450295,
    flags: { svg: "https://flagcdn.com/se.svg" },
    latlng: [60, 18],
    currencies: { SEK: { name: "Swedish krona" } },
    languages: { swe: "Swedish" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Hungary" },
    cca2: "HU",
    cca3: "HUN",
    capital: ["Budapest"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 9660000,
    area: 93028,
    flags: { svg: "https://flagcdn.com/hu.svg" },
    latlng: [47, 20],
    currencies: { HUF: { name: "Hungarian forint" } },
    languages: { hun: "Hungarian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Belarus" },
    cca2: "BY",
    cca3: "BLR",
    capital: ["Minsk"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 9449000,
    area: 207600,
    flags: { svg: "https://flagcdn.com/by.svg" },
    latlng: [53, 28],
    currencies: { BYN: { name: "Belarusian ruble" } },
    languages: { bel: "Belarusian", rus: "Russian" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Austria" },
    cca2: "AT",
    cca3: "AUT",
    capital: ["Vienna"],
    region: "Europe",
    subregion: "Western Europe",
    population: 8917000,
    area: 83879,
    flags: { svg: "https://flagcdn.com/at.svg" },
    latlng: [47, 16],
    currencies: { EUR: { name: "Euro" } },
    languages: { deu: "German" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Switzerland" },
    cca2: "CH",
    cca3: "CHE",
    capital: ["Bern"],
    region: "Europe",
    subregion: "Western Europe",
    population: 8632000,
    area: 41284,
    flags: { svg: "https://flagcdn.com/ch.svg" },
    latlng: [47, 8],
    currencies: { CHF: { name: "Swiss franc" } },
    languages: { deu: "German", fra: "French", ita: "Italian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Bulgaria" },
    cca2: "BG",
    cca3: "BGR",
    capital: ["Sofia"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 6927000,
    area: 110879,
    flags: { svg: "https://flagcdn.com/bg.svg" },
    latlng: [43, 25],
    currencies: { BGN: { name: "Bulgarian lev" } },
    languages: { bul: "Bulgarian" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Serbia" },
    cca2: "RS",
    cca3: "SRB",
    capital: ["Belgrade"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 6945000,
    area: 88361,
    flags: { svg: "https://flagcdn.com/rs.svg" },
    latlng: [44, 21],
    currencies: { RSD: { name: "Serbian dinar" } },
    languages: { srp: "Serbian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Denmark" },
    cca2: "DK",
    cca3: "DNK",
    capital: ["Copenhagen"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 5831000,
    area: 43094,
    flags: { svg: "https://flagcdn.com/dk.svg" },
    latlng: [56, 10],
    currencies: { DKK: { name: "Danish krone" } },
    languages: { dan: "Danish" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Finland" },
    cca2: "FI",
    cca3: "FIN",
    capital: ["Helsinki"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 5531000,
    area: 338424,
    flags: { svg: "https://flagcdn.com/fi.svg" },
    latlng: [64, 26],
    currencies: { EUR: { name: "Euro" } },
    languages: { fin: "Finnish", swe: "Swedish" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Norway" },
    cca2: "NO",
    cca3: "NOR",
    capital: ["Oslo"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 5379000,
    area: 323802,
    flags: { svg: "https://flagcdn.com/no.svg" },
    latlng: [60, 8],
    currencies: { NOK: { name: "Norwegian krone" } },
    languages: { nor: "Norwegian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Ireland" },
    cca2: "IE",
    cca3: "IRL",
    capital: ["Dublin"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 4938000,
    area: 70273,
    flags: { svg: "https://flagcdn.com/ie.svg" },
    latlng: [53, -8],
    currencies: { EUR: { name: "Euro" } },
    languages: { eng: "English", gle: "Irish" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Croatia" },
    cca2: "HR",
    cca3: "HRV",
    capital: ["Zagreb"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 4105000,
    area: 56594,
    flags: { svg: "https://flagcdn.com/hr.svg" },
    latlng: [45, 16],
    currencies: { EUR: { name: "Euro" } },
    languages: { hrv: "Croatian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Slovakia" },
    cca2: "SK",
    cca3: "SVK",
    capital: ["Bratislava"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 5459000,
    area: 49035,
    flags: { svg: "https://flagcdn.com/sk.svg" },
    latlng: [48, 19],
    currencies: { EUR: { name: "Euro" } },
    languages: { slk: "Slovak" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Bosnia and Herzegovina" },
    cca2: "BA",
    cca3: "BIH",
    capital: ["Sarajevo"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 3281000,
    area: 51197,
    flags: { svg: "https://flagcdn.com/ba.svg" },
    latlng: [44, 18],
    currencies: { BAM: { name: "Bosnia and Herzegovina convertible mark" } },
    languages: { bos: "Bosnian", hrv: "Croatian", srp: "Serbian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Albania" },
    cca2: "AL",
    cca3: "ALB",
    capital: ["Tirana"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 2877000,
    area: 28748,
    flags: { svg: "https://flagcdn.com/al.svg" },
    latlng: [41, 20],
    currencies: { ALL: { name: "Albanian lek" } },
    languages: { sqi: "Albanian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Lithuania" },
    cca2: "LT",
    cca3: "LTU",
    capital: ["Vilnius"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 2795000,
    area: 65300,
    flags: { svg: "https://flagcdn.com/lt.svg" },
    latlng: [56, 24],
    currencies: { EUR: { name: "Euro" } },
    languages: { lit: "Lithuanian" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Latvia" },
    cca2: "LV",
    cca3: "LVA",
    capital: ["Riga"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 1886000,
    area: 64500,
    flags: { svg: "https://flagcdn.com/lv.svg" },
    latlng: [57, 25],
    currencies: { EUR: { name: "Euro" } },
    languages: { lav: "Latvian" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Estonia" },
    cca2: "EE",
    cca3: "EST",
    capital: ["Tallinn"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 1329000,
    area: 45228,
    flags: { svg: "https://flagcdn.com/ee.svg" },
    latlng: [59, 26],
    currencies: { EUR: { name: "Euro" } },
    languages: { est: "Estonian" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Slovenia" },
    cca2: "SI",
    cca3: "SVN",
    capital: ["Ljubljana"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 2079000,
    area: 20273,
    flags: { svg: "https://flagcdn.com/si.svg" },
    latlng: [46, 15],
    currencies: { EUR: { name: "Euro" } },
    languages: { slv: "Slovenian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "North Macedonia" },
    cca2: "MK",
    cca3: "MKD",
    capital: ["Skopje"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 2077000,
    area: 25713,
    flags: { svg: "https://flagcdn.com/mk.svg" },
    latlng: [41, 22],
    currencies: { MKD: { name: "Macedonian denar" } },
    languages: { mkd: "Macedonian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Montenegro" },
    cca2: "ME",
    cca3: "MNE",
    capital: ["Podgorica"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 628000,
    area: 13812,
    flags: { svg: "https://flagcdn.com/me.svg" },
    latlng: [42, 19],
    currencies: { EUR: { name: "Euro" } },
    languages: { srp: "Serbian" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Luxembourg" },
    cca2: "LU",
    cca3: "LUX",
    capital: ["Luxembourg"],
    region: "Europe",
    subregion: "Western Europe",
    population: 634000,
    area: 2586,
    flags: { svg: "https://flagcdn.com/lu.svg" },
    latlng: [50, 6],
    currencies: { EUR: { name: "Euro" } },
    languages: { fra: "French", deu: "German", ltz: "Luxembourgish" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Malta" },
    cca2: "MT",
    cca3: "MLT",
    capital: ["Valletta"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 442000,
    area: 316,
    flags: { svg: "https://flagcdn.com/mt.svg" },
    latlng: [36, 14],
    currencies: { EUR: { name: "Euro" } },
    languages: { mlt: "Maltese", eng: "English" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Iceland" },
    cca2: "IS",
    cca3: "ISL",
    capital: ["Reykjavik"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 366000,
    area: 103000,
    flags: { svg: "https://flagcdn.com/is.svg" },
    latlng: [65, -18],
    currencies: { ISK: { name: "Icelandic króna" } },
    languages: { isl: "Icelandic" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Cyprus" },
    cca2: "CY",
    cca3: "CYP",
    capital: ["Nicosia"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 1198000,
    area: 9251,
    flags: { svg: "https://flagcdn.com/cy.svg" },
    latlng: [35, 33],
    currencies: { EUR: { name: "Euro" } },
    languages: { ell: "Greek", tur: "Turkish" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Russia" },
    cca2: "RU",
    cca3: "RUS",
    capital: ["Moscow"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 144400000,
    area: 17098242,
    flags: { svg: "https://flagcdn.com/ru.svg" },
    latlng: [61, 105],
    currencies: { RUB: { name: "Russian ruble" } },
    languages: { rus: "Russian" },
    timezones: ["UTC+03:00"],
    independent: true,
  },

  // Americas
  {
    name: { common: "United States" },
    cca2: "US",
    cca3: "USA",
    capital: ["Washington, D.C."],
    region: "Americas",
    subregion: "North America",
    population: 331000000,
    area: 9372610,
    flags: { svg: "https://flagcdn.com/us.svg" },
    latlng: [38, -97],
    currencies: { USD: { name: "United States dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Canada" },
    cca2: "CA",
    cca3: "CAN",
    capital: ["Ottawa"],
    region: "Americas",
    subregion: "North America",
    population: 38000000,
    area: 9984670,
    flags: { svg: "https://flagcdn.com/ca.svg" },
    latlng: [60, -95],
    currencies: { CAD: { name: "Canadian dollar" } },
    languages: { eng: "English", fra: "French" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Brazil" },
    cca2: "BR",
    cca3: "BRA",
    capital: ["Brasília"],
    region: "Americas",
    subregion: "South America",
    population: 212600000,
    area: 8515767,
    flags: { svg: "https://flagcdn.com/br.svg" },
    latlng: [-14, -51],
    currencies: { BRL: { name: "Brazilian real" } },
    languages: { por: "Portuguese" },
    timezones: ["UTC-03:00"],
    independent: true,
  },
  {
    name: { common: "Mexico" },
    cca2: "MX",
    cca3: "MEX",
    capital: ["Mexico City"],
    region: "Americas",
    subregion: "North America",
    population: 126700000,
    area: 1964375,
    flags: { svg: "https://flagcdn.com/mx.svg" },
    latlng: [23, -102],
    currencies: { MXN: { name: "Mexican peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-06:00"],
    independent: true,
  },
  {
    name: { common: "Argentina" },
    cca2: "AR",
    cca3: "ARG",
    capital: ["Buenos Aires"],
    region: "Americas",
    subregion: "South America",
    population: 45380000,
    area: 2780400,
    flags: { svg: "https://flagcdn.com/ar.svg" },
    latlng: [-34, -64],
    currencies: { ARS: { name: "Argentine peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-03:00"],
    independent: true,
  },
  {
    name: { common: "Colombia" },
    cca2: "CO",
    cca3: "COL",
    capital: ["Bogotá"],
    region: "Americas",
    subregion: "South America",
    population: 50880000,
    area: 1141748,
    flags: { svg: "https://flagcdn.com/co.svg" },
    latlng: [4, -72],
    currencies: { COP: { name: "Colombian peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Peru" },
    cca2: "PE",
    cca3: "PER",
    capital: ["Lima"],
    region: "Americas",
    subregion: "South America",
    population: 32970000,
    area: 1285216,
    flags: { svg: "https://flagcdn.com/pe.svg" },
    latlng: [-10, -76],
    currencies: { PEN: { name: "Peruvian sol" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Venezuela" },
    cca2: "VE",
    cca3: "VEN",
    capital: ["Caracas"],
    region: "Americas",
    subregion: "South America",
    population: 28440000,
    area: 916445,
    flags: { svg: "https://flagcdn.com/ve.svg" },
    latlng: [7, -66],
    currencies: { VES: { name: "Venezuelan bolívar" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Chile" },
    cca2: "CL",
    cca3: "CHL",
    capital: ["Santiago"],
    region: "Americas",
    subregion: "South America",
    population: 19120000,
    area: 756102,
    flags: { svg: "https://flagcdn.com/cl.svg" },
    latlng: [-30, -71],
    currencies: { CLP: { name: "Chilean peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Ecuador" },
    cca2: "EC",
    cca3: "ECU",
    capital: ["Quito"],
    region: "Americas",
    subregion: "South America",
    population: 17640000,
    area: 276841,
    flags: { svg: "https://flagcdn.com/ec.svg" },
    latlng: [-2, -78],
    currencies: { USD: { name: "United States dollar" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Guatemala" },
    cca2: "GT",
    cca3: "GTM",
    capital: ["Guatemala City"],
    region: "Americas",
    subregion: "Central America",
    population: 17110000,
    area: 108889,
    flags: { svg: "https://flagcdn.com/gt.svg" },
    latlng: [15, -90],
    currencies: { GTQ: { name: "Guatemalan quetzal" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-06:00"],
    independent: true,
  },
  {
    name: { common: "Cuba" },
    cca2: "CU",
    cca3: "CUB",
    capital: ["Havana"],
    region: "Americas",
    subregion: "Caribbean",
    population: 11330000,
    area: 109884,
    flags: { svg: "https://flagcdn.com/cu.svg" },
    latlng: [21, -80],
    currencies: { CUP: { name: "Cuban peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Haiti" },
    cca2: "HT",
    cca3: "HTI",
    capital: ["Port-au-Prince"],
    region: "Americas",
    subregion: "Caribbean",
    population: 11480000,
    area: 27750,
    flags: { svg: "https://flagcdn.com/ht.svg" },
    latlng: [19, -72],
    currencies: { HTG: { name: "Haitian gourde" } },
    languages: { fra: "French" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Dominican Republic" },
    cca2: "DO",
    cca3: "DOM",
    capital: ["Santo Domingo"],
    region: "Americas",
    subregion: "Caribbean",
    population: 10850000,
    area: 48671,
    flags: { svg: "https://flagcdn.com/do.svg" },
    latlng: [19, -70],
    currencies: { DOP: { name: "Dominican peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Bolivia" },
    cca2: "BO",
    cca3: "BOL",
    capital: ["Sucre"],
    region: "Americas",
    subregion: "South America",
    population: 11670000,
    area: 1098581,
    flags: { svg: "https://flagcdn.com/bo.svg" },
    latlng: [-17, -65],
    currencies: { BOB: { name: "Bolivian boliviano" } },
    languages: { spa: "Spanish", aym: "Aymara", que: "Quechua" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Paraguay" },
    cca2: "PY",
    cca3: "PRY",
    capital: ["Asunción"],
    region: "Americas",
    subregion: "South America",
    population: 7133000,
    area: 406752,
    flags: { svg: "https://flagcdn.com/py.svg" },
    latlng: [-23, -58],
    currencies: { PYG: { name: "Paraguayan guaraní" } },
    languages: { spa: "Spanish", gug: "Guaraní" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Uruguay" },
    cca2: "UY",
    cca3: "URY",
    capital: ["Montevideo"],
    region: "Americas",
    subregion: "South America",
    population: 3473000,
    area: 176215,
    flags: { svg: "https://flagcdn.com/uy.svg" },
    latlng: [-33, -56],
    currencies: { UYU: { name: "Uruguayan peso" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-03:00"],
    independent: true,
  },
  {
    name: { common: "Panama" },
    cca2: "PA",
    cca3: "PAN",
    capital: ["Panama City"],
    region: "Americas",
    subregion: "Central America",
    population: 4315000,
    area: 75417,
    flags: { svg: "https://flagcdn.com/pa.svg" },
    latlng: [9, -80],
    currencies: { PAB: { name: "Panamanian balboa" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Costa Rica" },
    cca2: "CR",
    cca3: "CRI",
    capital: ["San José"],
    region: "Americas",
    subregion: "Central America",
    population: 5094000,
    area: 51100,
    flags: { svg: "https://flagcdn.com/cr.svg" },
    latlng: [10, -84],
    currencies: { CRC: { name: "Costa Rican colón" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-06:00"],
    independent: true,
  },
  {
    name: { common: "Jamaica" },
    cca2: "JM",
    cca3: "JAM",
    capital: ["Kingston"],
    region: "Americas",
    subregion: "Caribbean",
    population: 2961000,
    area: 10991,
    flags: { svg: "https://flagcdn.com/jm.svg" },
    latlng: [18, -77],
    currencies: { JMD: { name: "Jamaican dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC-05:00"],
    independent: true,
  },
  {
    name: { common: "Trinidad and Tobago" },
    cca2: "TT",
    cca3: "TTO",
    capital: ["Port of Spain"],
    region: "Americas",
    subregion: "Caribbean",
    population: 1399000,
    area: 5128,
    flags: { svg: "https://flagcdn.com/tt.svg" },
    latlng: [11, -61],
    currencies: { TTD: { name: "Trinidad and Tobago dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Guyana" },
    cca2: "GY",
    cca3: "GUY",
    capital: ["Georgetown"],
    region: "Americas",
    subregion: "South America",
    population: 786000,
    area: 214969,
    flags: { svg: "https://flagcdn.com/gy.svg" },
    latlng: [5, -59],
    currencies: { GYD: { name: "Guyanaese dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Suriname" },
    cca2: "SR",
    cca3: "SUR",
    capital: ["Paramaribo"],
    region: "Americas",
    subregion: "South America",
    population: 586000,
    area: 163820,
    flags: { svg: "https://flagcdn.com/sr.svg" },
    latlng: [4, -56],
    currencies: { SRD: { name: "Surinamese dollar" } },
    languages: { nld: "Dutch" },
    timezones: ["UTC-03:00"],
    independent: true,
  },
  {
    name: { common: "Nicaragua" },
    cca2: "NI",
    cca3: "NIC",
    capital: ["Managua"],
    region: "Americas",
    subregion: "Central America",
    population: 6625000,
    area: 130373,
    flags: { svg: "https://flagcdn.com/ni.svg" },
    latlng: [13, -85],
    currencies: { NIO: { name: "Nicaraguan córdoba" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-06:00"],
    independent: true,
  },
  {
    name: { common: "Honduras" },
    cca2: "HN",
    cca3: "HND",
    capital: ["Tegucigalpa"],
    region: "Americas",
    subregion: "Central America",
    population: 9905000,
    area: 112492,
    flags: { svg: "https://flagcdn.com/hn.svg" },
    latlng: [15, -86],
    currencies: { HNL: { name: "Honduran lempira" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-06:00"],
    independent: true,
  },
  {
    name: { common: "El Salvador" },
    cca2: "SV",
    cca3: "SLV",
    capital: ["San Salvador"],
    region: "Americas",
    subregion: "Central America",
    population: 6825000,
    area: 21041,
    flags: { svg: "https://flagcdn.com/sv.svg" },
    latlng: [14, -89],
    currencies: { USD: { name: "United States dollar" } },
    languages: { spa: "Spanish" },
    timezones: ["UTC-06:00"],
    independent: true,
  },
  {
    name: { common: "Barbados" },
    cca2: "BB",
    cca3: "BRB",
    capital: ["Bridgetown"],
    region: "Americas",
    subregion: "Caribbean",
    population: 287000,
    area: 430,
    flags: { svg: "https://flagcdn.com/bb.svg" },
    latlng: [13, -59],
    currencies: { BBD: { name: "Barbadian dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC-04:00"],
    independent: true,
  },
  {
    name: { common: "Bahamas" },
    cca2: "BS",
    cca3: "BHS",
    capital: ["Nassau"],
    region: "Americas",
    subregion: "Caribbean",
    population: 393000,
    area: 13943,
    flags: { svg: "https://flagcdn.com/bs.svg" },
    latlng: [25, -77],
    currencies: { BSD: { name: "Bahamian dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC-05:00"],
    independent: true,
  },

  // Africa
  {
    name: { common: "Nigeria" },
    cca2: "NG",
    cca3: "NGA",
    capital: ["Abuja"],
    region: "Africa",
    subregion: "Western Africa",
    population: 206100000,
    area: 923768,
    flags: { svg: "https://flagcdn.com/ng.svg" },
    latlng: [10, 8],
    currencies: { NGN: { name: "Nigerian naira" } },
    languages: { eng: "English" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Egypt" },
    cca2: "EG",
    cca3: "EGY",
    capital: ["Cairo"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 104300000,
    area: 1010408,
    flags: { svg: "https://flagcdn.com/eg.svg" },
    latlng: [26, 30],
    currencies: { EGP: { name: "Egyptian pound" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "South Africa" },
    cca2: "ZA",
    cca3: "ZAF",
    capital: ["Pretoria"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 59310000,
    area: 1221037,
    flags: { svg: "https://flagcdn.com/za.svg" },
    latlng: [-30, 25],
    currencies: { ZAR: { name: "South African rand" } },
    languages: { eng: "English", afr: "Afrikaans", xho: "Xhosa", zul: "Zulu" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Ethiopia" },
    cca2: "ET",
    cca3: "ETH",
    capital: ["Addis Ababa"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 114900000,
    area: 1104300,
    flags: { svg: "https://flagcdn.com/et.svg" },
    latlng: [9, 39],
    currencies: { ETB: { name: "Ethiopian birr" } },
    languages: { amh: "Amharic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Democratic Republic of the Congo" },
    cca2: "CD",
    cca3: "COD",
    capital: ["Kinshasa"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 89560000,
    area: 2344858,
    flags: { svg: "https://flagcdn.com/cd.svg" },
    latlng: [-1, 23],
    currencies: { CDF: { name: "Congolese franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Tanzania" },
    cca2: "TZ",
    cca3: "TZA",
    capital: ["Dodoma"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 59730000,
    area: 947300,
    flags: { svg: "https://flagcdn.com/tz.svg" },
    latlng: [-6, 35],
    currencies: { TZS: { name: "Tanzanian shilling" } },
    languages: { swa: "Swahili", eng: "English" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Kenya" },
    cca2: "KE",
    cca3: "KEN",
    capital: ["Nairobi"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 53770000,
    area: 580367,
    flags: { svg: "https://flagcdn.com/ke.svg" },
    latlng: [0, 38],
    currencies: { KES: { name: "Kenyan shilling" } },
    languages: { eng: "English", swa: "Swahili" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Algeria" },
    cca2: "DZ",
    cca3: "DZA",
    capital: ["Algiers"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 43850000,
    area: 2381741,
    flags: { svg: "https://flagcdn.com/dz.svg" },
    latlng: [28, 1],
    currencies: { DZD: { name: "Algerian dinar" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Sudan" },
    cca2: "SD",
    cca3: "SDN",
    capital: ["Khartoum"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 43850000,
    area: 1861484,
    flags: { svg: "https://flagcdn.com/sd.svg" },
    latlng: [15, 30],
    currencies: { SDG: { name: "Sudanese pound" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Uganda" },
    cca2: "UG",
    cca3: "UGA",
    capital: ["Kampala"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 45740000,
    area: 241038,
    flags: { svg: "https://flagcdn.com/ug.svg" },
    latlng: [1, 32],
    currencies: { UGX: { name: "Ugandan shilling" } },
    languages: { eng: "English", swa: "Swahili" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Morocco" },
    cca2: "MA",
    cca3: "MAR",
    capital: ["Rabat"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 36910000,
    area: 446550,
    flags: { svg: "https://flagcdn.com/ma.svg" },
    latlng: [32, -6],
    currencies: { MAD: { name: "Moroccan dirham" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Angola" },
    cca2: "AO",
    cca3: "AGO",
    capital: ["Luanda"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 32870000,
    area: 1246700,
    flags: { svg: "https://flagcdn.com/ao.svg" },
    latlng: [-12, 18],
    currencies: { AOA: { name: "Angolan kwanza" } },
    languages: { por: "Portuguese" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Mozambique" },
    cca2: "MZ",
    cca3: "MOZ",
    capital: ["Maputo"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 31250000,
    area: 801590,
    flags: { svg: "https://flagcdn.com/mz.svg" },
    latlng: [-18, 35],
    currencies: { MZN: { name: "Mozambican metical" } },
    languages: { por: "Portuguese" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Ghana" },
    cca2: "GH",
    cca3: "GHA",
    capital: ["Accra"],
    region: "Africa",
    subregion: "Western Africa",
    population: 31070000,
    area: 238533,
    flags: { svg: "https://flagcdn.com/gh.svg" },
    latlng: [8, -2],
    currencies: { GHS: { name: "Ghanaian cedi" } },
    languages: { eng: "English" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Madagascar" },
    cca2: "MG",
    cca3: "MDG",
    capital: ["Antananarivo"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 27690000,
    area: 587041,
    flags: { svg: "https://flagcdn.com/mg.svg" },
    latlng: [-20, 47],
    currencies: { MGA: { name: "Malagasy ariary" } },
    languages: { mlg: "Malagasy", fra: "French" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Cameroon" },
    cca2: "CM",
    cca3: "CMR",
    capital: ["Yaoundé"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 26550000,
    area: 475442,
    flags: { svg: "https://flagcdn.com/cm.svg" },
    latlng: [7, 12],
    currencies: { XAF: { name: "Central African CFA franc" } },
    languages: { fra: "French", eng: "English" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Ivory Coast" },
    cca2: "CI",
    cca3: "CIV",
    capital: ["Yamoussoukro"],
    region: "Africa",
    subregion: "Western Africa",
    population: 26380000,
    area: 322463,
    flags: { svg: "https://flagcdn.com/ci.svg" },
    latlng: [8, -5],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Niger" },
    cca2: "NE",
    cca3: "NER",
    capital: ["Niamey"],
    region: "Africa",
    subregion: "Western Africa",
    population: 24110000,
    area: 1267000,
    flags: { svg: "https://flagcdn.ne.svg" },
    latlng: [16, 8],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Burkina Faso" },
    cca2: "BF",
    cca3: "BFA",
    capital: ["Ouagadougou"],
    region: "Africa",
    subregion: "Western Africa",
    population: 20970000,
    area: 274200,
    flags: { svg: "https://flagcdn.com/bf.svg" },
    latlng: [13, -2],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Mali" },
    cca2: "ML",
    cca3: "MLI",
    capital: ["Bamako"],
    region: "Africa",
    subregion: "Western Africa",
    population: 20250000,
    area: 1240192,
    flags: { svg: "https://flagcdn.com/ml.svg" },
    latlng: [17, -4],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Malawi" },
    cca2: "MW",
    cca3: "MWI",
    capital: ["Lilongwe"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 19130000,
    area: 118484,
    flags: { svg: "https://flagcdn.com/mw.svg" },
    latlng: [-14, 34],
    currencies: { MWK: { name: "Malawian kwacha" } },
    languages: { eng: "English", nya: "Chichewa" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Zambia" },
    cca2: "ZM",
    cca3: "ZMB",
    capital: ["Lusaka"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 18380000,
    area: 752618,
    flags: { svg: "https://flagcdn.com/zm.svg" },
    latlng: [-14, 30],
    currencies: { ZMW: { name: "Zambian kwacha" } },
    languages: { eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Senegal" },
    cca2: "SN",
    cca3: "SEN",
    capital: ["Dakar"],
    region: "Africa",
    subregion: "Western Africa",
    population: 16740000,
    area: 196722,
    flags: { svg: "https://flagcdn.com/sn.svg" },
    latlng: [14, -14],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Chad" },
    cca2: "TD",
    cca3: "TCD",
    capital: ["N'Djamena"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 16430000,
    area: 1284000,
    flags: { svg: "https://flagcdn.com/td.svg" },
    latlng: [15, 19],
    currencies: { XAF: { name: "Central African CFA franc" } },
    languages: { fra: "French", ara: "Arabic" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Somalia" },
    cca2: "SO",
    cca3: "SOM",
    capital: ["Mogadishu"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 15890000,
    area: 637657,
    flags: { svg: "https://flagcdn.com/so.svg" },
    latlng: [10, 49],
    currencies: { SOS: { name: "Somali shilling" } },
    languages: { som: "Somali", ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Zimbabwe" },
    cca2: "ZW",
    cca3: "ZWE",
    capital: ["Harare"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 14860000,
    area: 390757,
    flags: { svg: "https://flagcdn.com/zw.svg" },
    latlng: [-20, 30],
    currencies: { ZWL: { name: "Zimbabwean dollar" } },
    languages: { eng: "English", sna: "Shona", nde: "Northern Ndebele" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Guinea" },
    cca2: "GN",
    cca3: "GIN",
    capital: ["Conakry"],
    region: "Africa",
    subregion: "Western Africa",
    population: 13130000,
    area: 245857,
    flags: { svg: "https://flagcdn.com/gn.svg" },
    latlng: [11, -10],
    currencies: { GNF: { name: "Guinean franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Rwanda" },
    cca2: "RW",
    cca3: "RWA",
    capital: ["Kigali"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 12950000,
    area: 26338,
    flags: { svg: "https://flagcdn.com/rw.svg" },
    latlng: [-2, 30],
    currencies: { RWF: { name: "Rwandan franc" } },
    languages: { eng: "English", fra: "French", kin: "Kinyarwanda" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Benin" },
    cca2: "BJ",
    cca3: "BEN",
    capital: ["Porto-Novo"],
    region: "Africa",
    subregion: "Western Africa",
    population: 12120000,
    area: 112622,
    flags: { svg: "https://flagcdn.com/bj.svg" },
    latlng: [10, 2],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Burundi" },
    cca2: "BI",
    cca3: "BDI",
    capital: ["Gitega"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 11890000,
    area: 27834,
    flags: { svg: "https://flagcdn.com/bi.svg" },
    latlng: [-3, 30],
    currencies: { BIF: { name: "Burundian franc" } },
    languages: { fra: "French", eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Tunisia" },
    cca2: "TN",
    cca3: "TUN",
    capital: ["Tunis"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 11820000,
    area: 163610,
    flags: { svg: "https://flagcdn.com/tn.svg" },
    latlng: [34, 9],
    currencies: { TND: { name: "Tunisian dinar" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "South Sudan" },
    cca2: "SS",
    cca3: "SSD",
    capital: ["Juba"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 11190000,
    area: 644329,
    flags: { svg: "https://flagcdn.com/ss.svg" },
    latlng: [7, 30],
    currencies: { SSP: { name: "South Sudanese pound" } },
    languages: { eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Togo" },
    cca2: "TG",
    cca3: "TGO",
    capital: ["Lomé"],
    region: "Africa",
    subregion: "Western Africa",
    population: 8278000,
    area: 56785,
    flags: { svg: "https://flagcdn.com/tg.svg" },
    latlng: [8, 1],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Sierra Leone" },
    cca2: "SL",
    cca3: "SLE",
    capital: ["Freetown"],
    region: "Africa",
    subregion: "Western Africa",
    population: 8141000,
    area: 71740,
    flags: { svg: "https://flagcdn.com/sl.svg" },
    latlng: [8, -11],
    currencies: { SLL: { name: "Sierra Leonean leone" } },
    languages: { eng: "English" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Libya" },
    cca2: "LY",
    cca3: "LBY",
    capital: ["Tripoli"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 6987000,
    area: 1759540,
    flags: { svg: "https://flagcdn.com/ly.svg" },
    latlng: [27, 17],
    currencies: { LYD: { name: "Libyan dinar" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Congo" },
    cca2: "CG",
    cca3: "COG",
    capital: ["Brazzaville"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 5518000,
    area: 342000,
    flags: { svg: "https://flagcdn.com/cg.svg" },
    latlng: [-1, 15],
    currencies: { XAF: { name: "Central African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Liberia" },
    cca2: "LR",
    cca3: "LBR",
    capital: ["Monrovia"],
    region: "Africa",
    subregion: "Western Africa",
    population: 5057000,
    area: 111369,
    flags: { svg: "https://flagcdn.com/lr.svg" },
    latlng: [6, -9],
    currencies: { LRD: { name: "Liberian dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Central African Republic" },
    cca2: "CF",
    cca3: "CAF",
    capital: ["Bangui"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 4866000,
    area: 622984,
    flags: { svg: "https://flagcdn.com/cf.svg" },
    latlng: [7, 21],
    currencies: { XAF: { name: "Central African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Mauritania" },
    cca2: "MR",
    cca3: "MRT",
    capital: ["Nouakchott"],
    region: "Africa",
    subregion: "Western Africa",
    population: 4649000,
    area: 1030700,
    flags: { svg: "https://flagcdn.com/mr.svg" },
    latlng: [21, -10],
    currencies: { MRU: { name: "Mauritanian ouguiya" } },
    languages: { ara: "Arabic" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Eritrea" },
    cca2: "ER",
    cca3: "ERI",
    capital: ["Asmara"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 3546000,
    area: 117600,
    flags: { svg: "https://flagcdn.com/er.svg" },
    latlng: [15, 39],
    currencies: { ERN: { name: "Eritrean nakfa" } },
    languages: { ara: "Arabic", eng: "English" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Namibia" },
    cca2: "NA",
    cca3: "NAM",
    capital: ["Windhoek"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 2549000,
    area: 825615,
    flags: { svg: "https://flagcdn.com/na.svg" },
    latlng: [-22, 17],
    currencies: { NAD: { name: "Namibian dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Gambia" },
    cca2: "GM",
    cca3: "GMB",
    capital: ["Banjul"],
    region: "Africa",
    subregion: "Western Africa",
    population: 2417000,
    area: 11295,
    flags: { svg: "https://flagcdn.com/gm.svg" },
    latlng: [13, -16],
    currencies: { GMD: { name: "Gambian dalasi" } },
    languages: { eng: "English" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Botswana" },
    cca2: "BW",
    cca3: "BWA",
    capital: ["Gaborone"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 2319000,
    area: 582000,
    flags: { svg: "https://flagcdn.com/bw.svg" },
    latlng: [-22, 24],
    currencies: { BWP: { name: "Botswana pula" } },
    languages: { eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Gabon" },
    cca2: "GA",
    cca3: "GAB",
    capital: ["Libreville"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 2226000,
    area: 267668,
    flags: { svg: "https://flagcdn.com/ga.svg" },
    latlng: [-1, 12],
    currencies: { XAF: { name: "Central African CFA franc" } },
    languages: { fra: "French" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Lesotho" },
    cca2: "LS",
    cca3: "LSO",
    capital: ["Maseru"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 2142000,
    area: 30355,
    flags: { svg: "https://flagcdn.com/ls.svg" },
    latlng: [-29, 28],
    currencies: { LSL: { name: "Lesotho loti" } },
    languages: { eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Guinea-Bissau" },
    cca2: "GW",
    cca3: "GNB",
    capital: ["Bissau"],
    region: "Africa",
    subregion: "Western Africa",
    population: 1968000,
    area: 36125,
    flags: { svg: "https://flagcdn.com/gw.svg" },
    latlng: [12, -15],
    currencies: { XOF: { name: "West African CFA franc" } },
    languages: { por: "Portuguese" },
    timezones: ["UTC+00:00"],
    independent: true,
  },
  {
    name: { common: "Equatorial Guinea" },
    cca2: "GQ",
    cca3: "GNQ",
    capital: ["Malabo"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 1403000,
    area: 28051,
    flags: { svg: "https://flagcdn.com/gq.svg" },
    latlng: [2, 10],
    currencies: { XAF: { name: "Central African CFA franc" } },
    languages: { spa: "Spanish", fra: "French", por: "Portuguese" },
    timezones: ["UTC+01:00"],
    independent: true,
  },
  {
    name: { common: "Mauritius" },
    cca2: "MU",
    cca3: "MUS",
    capital: ["Port Louis"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 1266000,
    area: 2040,
    flags: { svg: "https://flagcdn.com/mu.svg" },
    latlng: [-20, 57],
    currencies: { MUR: { name: "Mauritian rupee" } },
    languages: { eng: "English" },
    timezones: ["UTC+04:00"],
    independent: true,
  },
  {
    name: { common: "Eswatini" },
    cca2: "SZ",
    cca3: "SWZ",
    capital: ["Mbabane"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 1160000,
    area: 17364,
    flags: { svg: "https://flagcdn.com/sz.svg" },
    latlng: [-26, 31],
    currencies: { SZL: { name: "Swazi lilangeni" } },
    languages: { eng: "English" },
    timezones: ["UTC+02:00"],
    independent: true,
  },
  {
    name: { common: "Djibouti" },
    cca2: "DJ",
    cca3: "DJI",
    capital: ["Djibouti"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 988000,
    area: 23200,
    flags: { svg: "https://flagcdn.com/dj.svg" },
    latlng: [11, 43],
    currencies: { DJF: { name: "Djiboutian franc" } },
    languages: { fra: "French", ara: "Arabic" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Comoros" },
    cca2: "KM",
    cca3: "COM",
    capital: ["Moroni"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 869000,
    area: 1862,
    flags: { svg: "https://flagcdn.com/km.svg" },
    latlng: [-12, 44],
    currencies: { KMF: { name: "Comorian franc" } },
    languages: { ara: "Arabic", fra: "French" },
    timezones: ["UTC+03:00"],
    independent: true,
  },
  {
    name: { common: "Cabo Verde" },
    cca2: "CV",
    cca3: "CPV",
    capital: ["Praia"],
    region: "Africa",
    subregion: "Western Africa",
    population: 555000,
    area: 4033,
    flags: { svg: "https://flagcdn.com/cv.svg" },
    latlng: [16, -24],
    currencies: { CVE: { name: "Cape Verdean escudo" } },
    languages: { por: "Portuguese" },
    timezones: ["UTC-01:00"],
    independent: true,
  },
  {
    name: { common: "Seychelles" },
    cca2: "SC",
    cca3: "SYC",
    capital: ["Victoria"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 98300,
    area: 462,
    flags: { svg: "https://flagcdn.com/sc.svg" },
    latlng: [-4, 55],
    currencies: { SCR: { name: "Seychellois rupee" } },
    languages: { eng: "English", fra: "French" },
    timezones: ["UTC+04:00"],
    independent: true,
  },

  // Oceania
  {
    name: { common: "Australia" },
    cca2: "AU",
    cca3: "AUS",
    capital: ["Canberra"],
    region: "Oceania",
    subregion: "Australia and New Zealand",
    population: 25690000,
    area: 7692024,
    flags: { svg: "https://flagcdn.com/au.svg" },
    latlng: [-25, 133],
    currencies: { AUD: { name: "Australian dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+10:00"],
    independent: true,
  },
  {
    name: { common: "Papua New Guinea" },
    cca2: "PG",
    cca3: "PNG",
    capital: ["Port Moresby"],
    region: "Oceania",
    subregion: "Melanesia",
    population: 8947000,
    area: 462840,
    flags: { svg: "https://flagcdn.com/pg.svg" },
    latlng: [-6, 143],
    currencies: { PGK: { name: "Papua New Guinean kina" } },
    languages: { eng: "English", tpi: "Tok Pisin" },
    timezones: ["UTC+10:00"],
    independent: true,
  },
  {
    name: { common: "New Zealand" },
    cca2: "NZ",
    cca3: "NZL",
    capital: ["Wellington"],
    region: "Oceania",
    subregion: "Australia and New Zealand",
    population: 5084000,
    area: 268838,
    flags: { svg: "https://flagcdn.com/nz.svg" },
    latlng: [-41, 174],
    currencies: { NZD: { name: "New Zealand dollar" } },
    languages: { eng: "English", mri: "Māori" },
    timezones: ["UTC+12:00"],
    independent: true,
  },
  {
    name: { common: "Fiji" },
    cca2: "FJ",
    cca3: "FJI",
    capital: ["Suva"],
    region: "Oceania",
    subregion: "Melanesia",
    population: 896000,
    area: 18274,
    flags: { svg: "https://flagcdn.com/fj.svg" },
    latlng: [-18, 178],
    currencies: { FJD: { name: "Fijian dollar" } },
    languages: { eng: "English", fij: "Fijian" },
    timezones: ["UTC+12:00"],
    independent: true,
  },
  {
    name: { common: "Solomon Islands" },
    cca2: "SB",
    cca3: "SLB",
    capital: ["Honiara"],
    region: "Oceania",
    subregion: "Melanesia",
    population: 686000,
    area: 28896,
    flags: { svg: "https://flagcdn.com/sb.svg" },
    latlng: [-8, 159],
    currencies: { SBD: { name: "Solomon Islands dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+11:00"],
    independent: true,
  },
  {
    name: { common: "Vanuatu" },
    cca2: "VU",
    cca3: "VUT",
    capital: ["Port Vila"],
    region: "Oceania",
    subregion: "Melanesia",
    population: 307000,
    area: 12189,
    flags: { svg: "https://flagcdn.com/vu.svg" },
    latlng: [-16, 167],
    currencies: { VUV: { name: "Vanuatu vatu" } },
    languages: { eng: "English", bis: "Bislama", fra: "French" },
    timezones: ["UTC+11:00"],
    independent: true,
  },
  {
    name: { common: "Samoa" },
    cca2: "WS",
    cca3: "WSM",
    capital: ["Apia"],
    region: "Oceania",
    subregion: "Polynesia",
    population: 198000,
    area: 2842,
    flags: { svg: "https://flagcdn.com/ws.svg" },
    latlng: [-14, -172],
    currencies: { WST: { name: "Samoan tālā" } },
    languages: { eng: "English", smo: "Samoan" },
    timezones: ["UTC+13:00"],
    independent: true,
  },
  {
    name: { common: "Kiribati" },
    cca2: "KI",
    cca3: "KIR",
    capital: ["Tarawa"],
    region: "Oceania",
    subregion: "Micronesia",
    population: 119000,
    area: 811,
    flags: { svg: "https://flagcdn.com/ki.svg" },
    latlng: [1, 173],
    currencies: { AUD: { name: "Australian dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+12:00"],
    independent: true,
  },
  {
    name: { common: "Tonga" },
    cca2: "TO",
    cca3: "TON",
    capital: ["Nukuʻalofa"],
    region: "Oceania",
    subregion: "Polynesia",
    population: 105000,
    area: 747,
    flags: { svg: "https://flagcdn.com/to.svg" },
    latlng: [-21, -175],
    currencies: { TOP: { name: "Tongan paʻanga" } },
    languages: { eng: "English", ton: "Tongan" },
    timezones: ["UTC+13:00"],
    independent: true,
  },
  {
    name: { common: "Micronesia" },
    cca2: "FM",
    cca3: "FSM",
    capital: ["Palikir"],
    region: "Oceania",
    subregion: "Micronesia",
    population: 115000,
    area: 702,
    flags: { svg: "https://flagcdn.com/fm.svg" },
    latlng: [7, 158],
    currencies: { USD: { name: "United States dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+10:00"],
    independent: true,
  },
  {
    name: { common: "Palau" },
    cca2: "PW",
    cca3: "PLW",
    capital: ["Ngerulmud"],
    region: "Oceania",
    subregion: "Micronesia",
    population: 18000,
    area: 459,
    flags: { svg: "https://flagcdn.com/pw.svg" },
    latlng: [7, 134],
    currencies: { USD: { name: "United States dollar" } },
    languages: { eng: "English" },
    timezones: ["UTC+09:00"],
    independent: true,
  },
  {
    name: { common: "Marshall Islands" },
    cca2: "MH",
    cca3: "MHL",
    capital: ["Majuro"],
    region: "Oceania",
    subregion: "Micronesia",
    population: 59000,
    area: 181,
    flags: { svg: "https://flagcdn.com/mh.svg" },
    latlng: [9, 168],
    currencies: { USD: { name: "United States dollar" } },
    languages: { eng: "English", mah: "Marshallese" },
    timezones: ["UTC+12:00"],
    independent: true,
  },
  {
    name: { common: "Nauru" },
    cca2: "NR",
    cca3: "NRU",
    capital: ["Yaren"],
    region: "Oceania",
    subregion: "Micronesia",
    population: 10800,
    area: 21,
    flags: { svg: "https://flagcdn.com/nr.svg" },
    latlng: [-0, 166],
    currencies: { AUD: { name: "Australian dollar" } },
    languages: { eng: "English", nau: "Nauruan" },
    timezones: ["UTC+12:00"],
    independent: true,
  },
  {
    name: { common: "Tuvalu" },
    cca2: "TV",
    cca3: "TUV",
    capital: ["Funafuti"],
    region: "Oceania",
    subregion: "Polynesia",
    population: 11700,
    area: 26,
    flags: { svg: "https://flagcdn.com/tv.svg" },
    latlng: [-8, 178],
    currencies: { AUD: { name: "Australian dollar" } },
    languages: { eng: "English", tvl: "Tuvaluan" },
    timezones: ["UTC+12:00"],
    independent: true,
  },
];

// Fetch all countries from the API
// If the API fails, we use our fallback data instead
export async function getAllCountries() {
  try {
    console.log("Fetching countries from API...");
    const response = await fetch(
      `${COUNTRIES_API_URL}/all?fields=${COUNTRY_FIELDS_TO_FETCH}`,
    );
    console.log("API response status:", response.status);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();

    if (!Array.isArray(data)) {
      throw new Error("Invalid data format");
    }

    console.log(`Successfully loaded ${data.length} countries from API`);

    // Sort countries alphabetically by name
    return data.sort((a, b) => a.name.common.localeCompare(b.name.common));
  } catch (error) {
    console.error("API Error, using fallback data:", error);
    // Use our backup data if the API fails
    return FALLBACK_COUNTRIES.sort((a, b) =>
      a.name.common.localeCompare(b.name.common),
    );
  }
}

// Fetch a single country by its code (e.g., 'US', 'GBR')
// Uses caching to avoid fetching the same country twice
export async function getCountryByCode(countryCode) {
  return fetchWithCache(`country-${countryCode}`, async () => {
    try {
      const response = await fetch(
        `${COUNTRIES_API_URL}/alpha/${countryCode}?fields=${COUNTRY_FIELDS_TO_FETCH}`,
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      return response.json();
    } catch (error) {
      console.error("Country API Error, using fallback:", error);

      // Try to find the country in our fallback data
      const fallbackCountry = FALLBACK_COUNTRIES.find(
        (country) =>
          country.cca3 === countryCode || country.cca2 === countryCode,
      );

      if (fallbackCountry) {
        return fallbackCountry;
      }

      throw new Error("Country not found");
    }
  });
}

// Fetch all countries in a specific region (e.g., 'Africa', 'Europe')
// Uses caching to avoid fetching the same region twice
export async function getCountriesByRegion(regionName) {
  return fetchWithCache(`region-${regionName}`, async () => {
    try {
      const response = await fetch(
        `${COUNTRIES_API_URL}/region/${regionName}?fields=${COUNTRY_FIELDS_TO_FETCH}`,
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      return response.json();
    } catch (error) {
      console.error("Region API Error, using fallback:", error);
      // Filter our fallback data for this region
      return FALLBACK_COUNTRIES.filter(
        (country) => country.region === regionName,
      );
    }
  });
}

// Search for countries by name
// If the search fails, we search through our fallback data instead
export async function searchCountriesByName(searchTerm) {
  if (!searchTerm?.trim()) {
    return [];
  }

  try {
    const response = await fetch(
      `${COUNTRIES_API_URL}/name/${encodeURIComponent(searchTerm)}?fields=${COUNTRY_FIELDS_TO_FETCH}`,
    );

    if (!response.ok) {
      return [];
    }

    return response.json();
  } catch (error) {
    console.error("Search API Error, using fallback:", error);

    // Search through our fallback data
    const lowerSearchTerm = searchTerm.toLowerCase();
    return FALLBACK_COUNTRIES.filter((country) =>
      country.name.common.toLowerCase().includes(lowerSearchTerm),
    );
  }
}

// ============================================
// WIKIPEDIA API FUNCTIONS - Travel guides and attractions
// ============================================

// Get a summary of a Wikipedia article (used for travel guides)
// Uses caching to avoid fetching the same article twice
export async function getWikiSummary(articleTitle) {
  return fetchWithCache(`wiki-summary-${articleTitle}`, async () => {
    const response = await fetch(
      `${WIKIPEDIA_SUMMARY_URL}/${encodeURIComponent(articleTitle)}`,
    );

    if (!response.ok) {
      throw new Error("No guide found");
    }

    return response.json();
  });
}

// Find nearby attractions around a location using Wikipedia's geosearch
// Returns places of interest within a certain radius of coordinates
export async function getAttractionsNear(
  latitude,
  longitude,
  radiusInMeters = 30000,
  maxResults = 12,
) {
  return fetchWithCache(`geosearch-${latitude}-${longitude}`, async () => {
    const searchParams = new URLSearchParams({
      action: "query",
      list: "geosearch",
      gscoord: `${latitude}|${longitude}`,
      gsradius: String(Math.min(radiusInMeters, 10000)), // Wikipedia limits to 10km
      gslimit: String(maxResults),
      format: "json",
      origin: "*",
    });

    const response = await fetch(
      `${WIKIPEDIA_API_URL}?${searchParams.toString()}`,
    );

    if (!response.ok) {
      throw new Error("Failed to load attractions");
    }

    const data = await response.json();
    return data.query?.geosearch ?? [];
  });
}

// Get detailed information for multiple Wikipedia articles at once
// Used to get descriptions and thumbnails for attractions
export async function getWikipediaDetailsBatch(articleTitles) {
  if (!articleTitles.length) {
    return {};
  }

  const searchParams = new URLSearchParams({
    action: "query",
    prop: "extracts|pageimages",
    exintro: "1",
    explaintext: "1",
    exsentences: "2",
    piprop: "thumbnail",
    pithumbsize: "400",
    titles: articleTitles.join("|"),
    format: "json",
    origin: "*",
  });

  const response = await fetch(
    `${WIKIPEDIA_API_URL}?${searchParams.toString()}`,
  );

  if (!response.ok) {
    return {};
  }

  const data = await response.json();
  return data.query?.pages ?? {};
}

// ---------- Unsplash photography ----------

const FALLBACK_IMAGE_SEEDS = [
  "travel",
  "mountains",
  "coastline",
  "old-town",
  "skyline",
  "desert",
  "forest",
  "harbor",
];

export function fallbackImage(seed, w = 800, h = 600) {
  const s = encodeURIComponent(seed || FALLBACK_IMAGE_SEEDS[0]);
  return `https://picsum.photos/seed/${s}/${w}/${h}`;
}

export async function getUnsplashPhoto(
  query,
  { width = 800, height = 600 } = {},
) {
  if (!UNSPLASH_API_KEY) {
    return {
      url: fallbackImage(query, width, height),
      credit: null,
      isFallback: true,
    };
  }
  return fetchWithCache(`unsplash-${query}-${width}x${height}`, async () => {
    try {
      const params = new URLSearchParams({
        query,
        orientation: width >= height ? "landscape" : "portrait",
        content_filter: "high",
      });
      const res = await fetch(
        `https://api.unsplash.com/photos/random?${params.toString()}`,
        {
          headers: { Authorization: `Client-ID ${UNSPLASH_API_KEY}` },
        },
      );
      if (!res.ok) throw new Error("Unsplash error");
      const data = await res.json();
      return {
        url: `${data.urls.raw}&w=${width}&h=${height}&fit=crop&q=80`,
        credit: { name: data.user?.name, link: data.user?.links?.html },
        isFallback: false,
      };
    } catch {
      return {
        url: fallbackImage(query, width, height),
        credit: null,
        isFallback: true,
      };
    }
  });
}

export function flagEmoji(cca2) {
  if (!cca2) return "";
  return cca2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

export function formatCoords(lat, lng) {
  if (lat == null || lng == null) return "—";
  const ns = lat >= 0 ? "N" : "S";
  const ew = lng >= 0 ? "E" : "W";
  return `${Math.abs(lat).toFixed(2)}°${ns} ${Math.abs(lng).toFixed(2)}°${ew}`;
}
